version: "3.8"

services:
  db:
    image: timescale/timescaledb-ha:pg17
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./infra/db/:/docker-entrypoint-initdb.d/init_scripts
    ports:
      - "5433:5432"

  db-init:
    image: timescale/timescaledb-ha:pg17
    depends_on:
      - db
    volumes:
      - ./infra/db:/init-scripts:ro
      - ./infra/db/init.sh:/run-init.sh:ro
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=password
    command: ["/run-init.sh"]
    restart: "no"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=postgres
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - db

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./fe:/app
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    command: >
      sh -c "npm run dev"